window.database.KhayDungDo = [
  { img: './images/KhayDungDo/3.png', name: '', description: '' },
  { img: './images/KhayDungDo/4.png', name: '', description: '' },
  { img: './images/KhayDungDo/5.png', name: '', description: '' },
  { img: './images/KhayDungDo/6.png', name: '', description: '' },
  { img: './images/KhayDungDo/7.png', name: '', description: '' },
  { img: './images/KhayDungDo/8.png', name: '', description: '' },
  { img: './images/KhayDungDo/13.png', name: '', description: '' },
  { img: './images/KhayDungDo/14.png', name: '', description: '' },
  { img: './images/KhayDungDo/15.png', name: '', description: '' },
  // {
  //   img: './images/KhayDungDo/20dd3640a415462bb57ee5469fb9c3a3.mov',
  //   name: '',
  //   description: '',
  // },
  // {
  //   img: './images/KhayDungDo/aa963c87c8314909a43fc9f78eb93315.mov',
  //   name: '',
  //   description: '',
  // },
  { img: './images/KhayDungDo/IMG_4552.JPG', name: '', description: '' },
  { img: './images/KhayDungDo/IMG_4558.JPG', name: '', description: '' },
  { img: './images/KhayDungDo/IMG_4561.JPG', name: '', description: '' },
  { img: './images/KhayDungDo/IMG_4562.JPG', name: '', description: '' },
  { img: './images/KhayDungDo/IMG_4566.JPG', name: '', description: '' },
  { img: './images/KhayDungDo/IMG_7365.JPG', name: '', description: '' },
  { img: './images/KhayDungDo/IMG_7368.JPG', name: '', description: '' },
  { img: './images/KhayDungDo/IMG_7375.JPG', name: '', description: '' },
  { img: './images/KhayDungDo/IMG_7376.JPG', name: '', description: '' },
  { img: './images/KhayDungDo/IMG_7385.JPG', name: '', description: '' },
  { img: './images/KhayDungDo/IMG_7386.JPG', name: '', description: '' },
  { img: './images/KhayDungDo/IMG_7388.JPG', name: '', description: '' },
  { img: './images/KhayDungDo/IMG_7392.JPG', name: '', description: '' },
  { img: './images/KhayDungDo/IMG_7393.JPG', name: '', description: '' },
  { img: './images/KhayDungDo/IMG_7396.JPG', name: '', description: '' },
  { img: './images/KhayDungDo/IMG_7398.JPG', name: '', description: '' },
  { img: './images/KhayDungDo/IMG_7399.JPG', name: '', description: '' },
  { img: './images/KhayDungDo/IMG_7400.JPG', name: '', description: '' },
  { img: './images/KhayDungDo/IMG_7401.JPG', name: '', description: '' },
  { img: './images/KhayDungDo/IMG_7402.JPG', name: '', description: '' },
];
